In [4]:
import pandas as pd
import numpy as np
from pathlib import Path

DATA_DIR = Path('../data')
WEATHER_DIR = DATA_DIR / 'raw/weather'

# ── List all files in weather folder ─────────────────────────────────────
print("── Files in weather folder ──")
for f in sorted(WEATHER_DIR.iterdir()):
    print(f"  {f.name}  ({f.stat().st_size / 1e6:.1f} MB)")

── Files in weather folder ──
  .DS_Store  (0.0 MB)
  .gitkeep  (0.0 MB)
  climate_combined.csv  (1.1 MB)
  weather_complete.csv  (14.9 MB)

In [5]:
# ── Inspect climate_combined.csv ─────────────────────────────────────────
cc = pd.read_csv(WEATHER_DIR / 'climate_combined.csv')

print(f"Shape: {cc.shape[0]:,} rows × {cc.shape[1]} columns")

print(f"\\n── All Columns ──")
for i, col in enumerate(cc.columns):
    print(f"  {i:2d}. {col}")

print(f"\\n── Dtypes ──")
print(cc.dtypes.to_string())

print(f"\\n── Date Range ──")
# Try to find a date/time column automatically
date_cols = [c for c in cc.columns if any(k in c.lower() for k in ['date','time','year','month'])]
print(f"  Date-like columns: {date_cols}")
for col in date_cols[:3]:
    try:
        parsed = pd.to_datetime(cc[col], errors='coerce')
        print(f"  {col}: {parsed.min()} → {parsed.max()}")
    except:
        print(f"  {col}: {cc[col].min()} → {cc[col].max()}")

print(f"\\n── Missing Values ──")
miss = cc.isnull().sum()
miss_pct = (miss / len(cc) * 100).round(1)
miss_df = pd.DataFrame({'missing': miss, 'pct': miss_pct})
print(miss_df[miss_df['missing'] > 0].to_string())

print(f"\\n── First 3 rows ──")
cc.head(3)

Shape: 8,760 rows × 31 columns
\n── All Columns ──
   0. ﻿"Longitude (x)"
   1. Latitude (y)
   2. Station Name
   3. Climate ID
   4. Date/Time (LST)
   5. Year
   6. Month
   7. Day
   8. Time (LST)
   9. Flag
  10. Temp (°C)
  11. Temp Flag
  12. Dew Point Temp (°C)
  13. Dew Point Temp Flag
  14. Rel Hum (%)
  15. Rel Hum Flag
  16. Precip. Amount (mm)
  17. Precip. Amount Flag
  18. Wind Dir (10s deg)
  19. Wind Dir Flag
  20. Wind Spd (km/h)
  21. Wind Spd Flag
  22. Visibility (km)
  23. Visibility Flag
  24. Stn Press (kPa)
  25. Stn Press Flag
  26. Hmdx
  27. Hmdx Flag
  28. Wind Chill
  29. Wind Chill Flag
  30. Weather
\n── Dtypes ──
﻿"Longitude (x)"       float64
Latitude (y)           float64
Station Name               str
Climate ID               int64
Date/Time (LST)            str
Year                     int64
Month                    int64
Day                      int64
Time (LST)                 str
Flag                   float64
Temp (°C)              float64
Temp Flag              float64
Dew Point Temp (°C)    float64
Dew Point Temp Flag    float64
Rel Hum (%)            float64
Rel Hum Flag           float64
Precip. Amount (mm)    float64
Precip. Amount Flag        str
Wind Dir (10s deg)     float64
Wind Dir Flag              str
Wind Spd (km/h)        float64
Wind Spd Flag              str
Visibility (km)        float64
Visibility Flag            str
Stn Press (kPa)        float64
Stn Press Flag         float64
Hmdx                   float64
Hmdx Flag              float64
Wind Chill             float64
Wind Chill Flag        float64
Weather                    str
\n── Date Range ──
  Date-like columns: ['Date/Time (LST)', 'Year', 'Month', 'Time (LST)']
  Date/Time (LST): 2025-01-01 00:00:00 → 2025-12-31 23:00:00
  Year: 1970-01-01 00:00:00.000002025 → 1970-01-01 00:00:00.000002025
  Month: 1970-01-01 00:00:00.000000001 → 1970-01-01 00:00:00.000000012
\n── Missing Values ──
                     missing    pct
Flag                    8760  100.0
Temp (°C)                 20    0.2
Temp Flag               8760  100.0
Dew Point Temp (°C)       20    0.2
Dew Point Temp Flag     8760  100.0
Rel Hum (%)               20    0.2
Rel Hum Flag            8760  100.0
Precip. Amount (mm)       27    0.3
Precip. Amount Flag     8753   99.9
Wind Dir (10s deg)       554    6.3
Wind Dir Flag           8486   96.9
Wind Spd (km/h)           35    0.4
Wind Spd Flag           8745   99.8
Visibility (km)           23    0.3
Visibility Flag         8757  100.0
Stn Press (kPa)           20    0.2
Stn Press Flag          8760  100.0
Hmdx                    7368   84.1
Hmdx Flag               8760  100.0
Wind Chill              6846   78.2
Wind Chill Flag         8760  100.0
Weather                 7521   85.9
\n── First 3 rows ──

,"﻿""Longitude (x)""",Latitude (y),Station Name,Climate ID,Date/Time (LST),Year,Month,Day,Time (LST),Flag,...,Wind Spd Flag,Visibility (km),Visibility Flag,Stn Press (kPa),Stn Press Flag,Hmdx,Hmdx Flag,Wind Chill,Wind Chill Flag,Weather
0,-79.4,43.63,TORONTO CITY CENTRE,6158359,2025-01-01 00:00,2025,1,1,00:00,NaN,...,NaN,16.1,NaN,99.04,NaN,NaN,NaN,NaN,NaN,Rain
1,-79.4,43.63,TORONTO CITY CENTRE,6158359,2025-01-01 01:00,2025,1,1,01:00,NaN,...,NaN,16.1,NaN,99.05,NaN,NaN,NaN,NaN,NaN,Rain
2,-79.4,43.63,TORONTO CITY CENTRE,6158359,2025-01-01 02:00,2025,1,1,02:00,NaN,...,NaN,16.1,NaN,99.09,NaN,NaN,NaN,NaN,NaN,Rain

In [6]:
# ── Inspect weather_complete.csv ─────────────────────────────────────────
wc = pd.read_csv(WEATHER_DIR / 'weather_complete.csv')

print(f"Shape: {wc.shape[0]:,} rows × {wc.shape[1]} columns")

print(f"\\n── All Columns ──")
for i, col in enumerate(wc.columns):
    print(f"  {i:2d}. {col}")

print(f"\\n── Date Range ──")
wc['Date/Time (LST)'] = pd.to_datetime(wc['Date/Time (LST)'])
print(f"  Start  : {wc['Date/Time (LST)'].min()}")
print(f"  End    : {wc['Date/Time (LST)'].max()}")
print(f"  Years  : {sorted(wc['Year'].unique())}")

print(f"\\n── 2025 Coverage ──")
wc25 = wc[wc['Year'] == 2025]
print(f"  2025 rows     : {len(wc25):,}")
print(f"  2025 months   : {sorted(wc25['Month'].unique())}")
print(f"  Expected hrs  : {365*24:,}")
print(f"  Coverage      : {len(wc25)/(365*24)*100:.1f}%")

print(f"\\n── Missing Values (full dataset) ──")
miss = wc.isnull().sum()
miss_pct = (miss / len(wc) * 100).round(1)
miss_df = pd.DataFrame({'missing': miss, 'pct': miss_pct})
print(miss_df[miss_df['missing'] > 0].to_string())

print(f"\\n── Station Info ──")
print(f"  Stations   : {wc['Station Name'].unique()}")
print(f"  Climate IDs: {wc['Climate ID'].unique()}")

print(f"\\n── First 3 rows ──")
wc.head(3)

Shape: 105,192 rows × 32 columns
\n── All Columns ──
   0. Longitude (x)
   1. Latitude (y)
   2. Station Name
   3. Climate ID
   4. Date/Time (LST)
   5. Year
   6. Month
   7. Day
   8. Time (LST)
   9. Flag
  10. Temp (°C)
  11. Temp Flag
  12. Dew Point Temp (°C)
  13. Dew Point Temp Flag
  14. Rel Hum (%)
  15. Rel Hum Flag
  16. Precip. Amount (mm)
  17. Precip. Amount Flag
  18. Wind Dir (10s deg)
  19. Wind Dir Flag
  20. Wind Spd (km/h)
  21. Wind Spd Flag
  22. Visibility (km)
  23. Visibility Flag
  24. Stn Press (kPa)
  25. Stn Press Flag
  26. Hmdx
  27. Hmdx Flag
  28. Wind Chill
  29. Wind Chill Flag
  30. Weather
  31. source_file
\n── Date Range ──
  Start  : 2014-01-01 00:00:00
  End    : 2025-12-31 23:00:00
  Years  : [np.int64(2014), np.int64(2015), np.int64(2016), np.int64(2017), np.int64(2018), np.int64(2019), np.int64(2020), np.int64(2021), np.int64(2022), np.int64(2023), np.int64(2024), np.int64(2025)]
\n── 2025 Coverage ──
  2025 rows     : 8,760
  2025 months   : [np.int64(1), np.int64(2), np.int64(3), np.int64(4), np.int64(5), np.int64(6), np.int64(7), np.int64(8), np.int64(9), np.int64(10), np.int64(11), np.int64(12)]
  Expected hrs  : 8,760
  Coverage      : 100.0%
\n── Missing Values (full dataset) ──
                     missing    pct
Flag                  105192  100.0
Temp (°C)                 29    0.0
Temp Flag             105190  100.0
Dew Point Temp (°C)       30    0.0
Dew Point Temp Flag   105188  100.0
Rel Hum (%)               35    0.0
Rel Hum Flag          105183  100.0
Precip. Amount (mm)   105192  100.0
Precip. Amount Flag   105192  100.0
Wind Dir (10s deg)      1862    1.8
Wind Dir Flag         105189  100.0
Wind Spd (km/h)           30    0.0
Wind Spd Flag         105188  100.0
Visibility (km)           27    0.0
Visibility Flag       105191  100.0
Stn Press (kPa)           28    0.0
Stn Press Flag        105190  100.0
Hmdx                   87248   82.9
Hmdx Flag             105192  100.0
Wind Chill             82724   78.6
Wind Chill Flag       105192  100.0
Weather                59811   56.9
\n── Station Info ──
  Stations   : <ArrowStringArray>
['TORONTO INTL A']
Length: 1, dtype: str
  Climate IDs: [6158731]
\n── First 3 rows ──

/var/folders/vx/1z8stp8j3pq2bhjy2bl6rg_c0000gn/T/ipykernel_30407/253340323.py:2: DtypeWarning: Columns (0: Temp Flag, 1: Dew Point Temp Flag, 2: Rel Hum Flag, 3: Wind Dir Flag, 4: Wind Spd Flag, 5: Visibility Flag, 6: Stn Press Flag) have mixed types. Specify dtype option on import or set low_memory=False.
  wc = pd.read_csv(WEATHER_DIR / 'weather_complete.csv')

,Longitude (x),Latitude (y),Station Name,Climate ID,Date/Time (LST),Year,Month,Day,Time (LST),Flag,...,Visibility (km),Visibility Flag,Stn Press (kPa),Stn Press Flag,Hmdx,Hmdx Flag,Wind Chill,Wind Chill Flag,Weather,source_file
0,-79.63,43.68,TORONTO INTL A,6158731,2014-01-01 00:00:00,2014,1,1,00:00,NaN,...,24.1,NaN,100.25,NaN,NaN,NaN,-18.0,NaN,NaN,weather_2014_01.csv
1,-79.63,43.68,TORONTO INTL A,6158731,2014-01-01 01:00:00,2014,1,1,01:00,NaN,...,24.1,NaN,100.32,NaN,NaN,NaN,-19.0,NaN,Mainly Clear,weather_2014_01.csv
2,-79.63,43.68,TORONTO INTL A,6158731,2014-01-01 02:00:00,2014,1,1,02:00,NaN,...,24.1,NaN,100.38,NaN,NaN,NaN,-19.0,NaN,NaN,weather_2014_01.csv

In [9]:
cc = pd.read_csv(WEATHER_DIR / 'climate_combined.csv')
wc = pd.read_csv(WEATHER_DIR / 'weather_complete.csv')

print("── climate_combined columns (repr) ──")
for col in cc.columns:
    print(repr(col))

print("\\n── weather_complete columns (repr) ──")
for col in wc.columns:
    print(repr(col))

── climate_combined columns (repr) ──
'\ufeff"Longitude (x)"'
'Latitude (y)'
'Station Name'
'Climate ID'
'Date/Time (LST)'
'Year'
'Month'
'Day'
'Time (LST)'
'Flag'
'Temp (°C)'
'Temp Flag'
'Dew Point Temp (°C)'
'Dew Point Temp Flag'
'Rel Hum (%)'
'Rel Hum Flag'
'Precip. Amount (mm)'
'Precip. Amount Flag'
'Wind Dir (10s deg)'
'Wind Dir Flag'
'Wind Spd (km/h)'
'Wind Spd Flag'
'Visibility (km)'
'Visibility Flag'
'Stn Press (kPa)'
'Stn Press Flag'
'Hmdx'
'Hmdx Flag'
'Wind Chill'
'Wind Chill Flag'
'Weather'
\n── weather_complete columns (repr) ──
'Longitude (x)'
'Latitude (y)'
'Station Name'
'Climate ID'
'Date/Time (LST)'
'Year'
'Month'
'Day'
'Time (LST)'
'Flag'
'Temp (°C)'
'Temp Flag'
'Dew Point Temp (°C)'
'Dew Point Temp Flag'
'Rel Hum (%)'
'Rel Hum Flag'
'Precip. Amount (mm)'
'Precip. Amount Flag'
'Wind Dir (10s deg)'
'Wind Dir Flag'
'Wind Spd (km/h)'
'Wind Spd Flag'
'Visibility (km)'
'Visibility Flag'
'Stn Press (kPa)'
'Stn Press Flag'
'Hmdx'
'Hmdx Flag'
'Wind Chill'
'Wind Chill Flag'
'Weather'
'source_file'

/var/folders/vx/1z8stp8j3pq2bhjy2bl6rg_c0000gn/T/ipykernel_30407/2606144837.py:2: DtypeWarning: Columns (0: Temp Flag, 1: Dew Point Temp Flag, 2: Rel Hum Flag, 3: Wind Dir Flag, 4: Wind Spd Flag, 5: Visibility Flag, 6: Stn Press Flag) have mixed types. Specify dtype option on import or set low_memory=False.
  wc = pd.read_csv(WEATHER_DIR / 'weather_complete.csv')

In [10]:
import math
import pandas as pd
from pathlib import Path

DATA_DIR = Path('../data')
WEATHER_DIR = DATA_DIR / 'raw/weather'

cc = pd.read_csv(WEATHER_DIR / 'climate_combined.csv')
wc = pd.read_csv(WEATHER_DIR / 'weather_complete.csv', low_memory=False)

cc['Date/Time (LST)'] = pd.to_datetime(cc['Date/Time (LST)'])
wc['Date/Time (LST)'] = pd.to_datetime(wc['Date/Time (LST)'])

# Auto-find lat/lon columns (handles encoding differences in column names)
def find_col(df, keyword):
    matches = [c for c in df.columns if keyword.lower() in c.lower()]
    return matches[0] if matches else None

cc_lon = find_col(cc, 'longitude')
cc_lat = find_col(cc, 'latitude')
wc_lon = find_col(wc, 'longitude')
wc_lat = find_col(wc, 'latitude')

KEY_COLS = [
    'Temp (°C)', 'Dew Point Temp (°C)', 'Rel Hum (%)',
    'Wind Dir (10s deg)', 'Wind Spd (km/h)',
    'Visibility (km)', 'Stn Press (kPa)',
    'Wind Chill', 'Hmdx', 'Weather'
]

print("=" * 65)
print(f"{'ATTRIBUTE':<30} {'climate_combined':>16} {'weather_complete':>16}")
print("=" * 65)

print(f"{'Rows':<30} {len(cc):>16,} {len(wc):>16,}")
print(f"{'Columns':<30} {cc.shape[1]:>16} {wc.shape[1]:>16}")
print(f"{'Station':<30} {'City Centre':>16} {'Pearson Intl':>16}")
print(f"{'Climate ID':<30} {str(cc['Climate ID'].iloc[0]):>16} {str(wc['Climate ID'].iloc[0]):>16}")
print(f"{'Latitude':<30} {cc[cc_lat].iloc[0]:>16.2f} {wc[wc_lat].iloc[0]:>16.2f}")
print(f"{'Longitude':<30} {cc[cc_lon].iloc[0]:>16.2f} {wc[wc_lon].iloc[0]:>16.2f}")
print(f"{'Date start':<30} {str(cc['Date/Time (LST)'].min())[:16]:>16} {str(wc['Date/Time (LST)'].min())[:16]:>16}")
print(f"{'Date end':<30} {str(cc['Date/Time (LST)'].max())[:16]:>16} {str(wc['Date/Time (LST)'].max())[:16]:>16}")

cc25 = cc[cc['Year'] == 2025]
wc25 = wc[wc['Year'] == 2025]
expected = 365 * 24

print(f"{'2025 rows':<30} {len(cc25):>16,} {len(wc25):>16,}")
print(f"{'2025 months covered':<30} {len(cc25['Month'].unique()):>16} {len(wc25['Month'].unique()):>16}")
print(f"{'2025 hour coverage %':<30} {len(cc25)/expected*100:>15.1f}% {len(wc25)/expected*100:>15.1f}%")

print(f"\\n── Missing rate on key columns (2025 only) ──")
print(f"  {'Column':<28} {'climate_combined':>16} {'weather_complete':>16}")
print("  " + "-" * 62)
for col in KEY_COLS:
    cc_miss = f"{cc25[col].isnull().mean()*100:.1f}%" if col in cc25.columns else "N/A"
    wc_miss = f"{wc25[col].isnull().mean()*100:.1f}%" if col in wc25.columns else "N/A"
    print(f"  {col:<28} {cc_miss:>16} {wc_miss:>16}")

cc_only = set(cc.columns) - set(wc.columns)
wc_only = set(wc.columns) - set(cc.columns)
print(f"\\n── Columns unique to climate_combined : {cc_only}")
print(f"── Columns unique to weather_complete : {wc_only}")

lat1, lon1 = cc[cc_lat].iloc[0], cc[cc_lon].iloc[0]
lat2, lon2 = wc[wc_lat].iloc[0], wc[wc_lon].iloc[0]
dlat = math.radians(lat2 - lat1)
dlon = math.radians(lon2 - lon1)
a = (math.sin(dlat/2)**2 +
     math.cos(math.radians(lat1)) * math.cos(math.radians(lat2)) * math.sin(dlon/2)**2)
dist_km = 6371 * 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
print(f"\\n── Distance between stations: {dist_km:.1f} km")

=================================================================
ATTRIBUTE                      climate_combined weather_complete
=================================================================
Rows                                      8,760          105,192
Columns                                      31               32
Station                             City Centre     Pearson Intl
Climate ID                              6158359          6158731
Latitude                                  43.63            43.68
Longitude                                -79.40           -79.63
Date start                     2025-01-01 00:00 2014-01-01 00:00
Date end                       2025-12-31 23:00 2025-12-31 23:00
2025 rows                                 8,760            8,760
2025 months covered                          12               12
2025 hour coverage %                     100.0%           100.0%
\n── Missing rate on key columns (2025 only) ──
  Column                       climate_combined weather_complete
  --------------------------------------------------------------
  Temp (°C)                                0.2%             0.0%
  Dew Point Temp (°C)                      0.2%             0.0%
  Rel Hum (%)                              0.2%             0.0%
  Wind Dir (10s deg)                       6.3%             1.8%
  Wind Spd (km/h)                          0.4%             0.0%
  Visibility (km)                          0.3%             0.0%
  Stn Press (kPa)                          0.2%             0.0%
  Wind Chill                              78.2%            74.7%
  Hmdx                                    84.1%            82.6%
  Weather                                 85.9%            56.8%
\n── Columns unique to climate_combined : {'\ufeff"Longitude (x)"'}
── Columns unique to weather_complete : {'source_file', 'Longitude (x)'}
\n── Distance between stations: 19.3 km

In [11]:
# ── Cell 5: Clean, merge, feature-engineer → save weather_2025.parquet ───
import pandas as pd
import numpy as np
from pathlib import Path

DATA_DIR  = Path('../data')
WEATHER_DIR = DATA_DIR / 'raw/weather'
OUT_DIR   = DATA_DIR / 'processed'
OUT_DIR.mkdir(parents=True, exist_ok=True)

# ── Load both ─────────────────────────────────────────────────────────────
wc = pd.read_csv(WEATHER_DIR / 'weather_complete.csv',  low_memory=False)
cc = pd.read_csv(WEATHER_DIR / 'climate_combined.csv')

# Fix BOM in climate_combined longitude column
cc.columns = [c.lstrip('\\ufeff').strip('"') for c in cc.columns]

# Parse datetime
wc['datetime'] = pd.to_datetime(wc['Date/Time (LST)'])
cc['datetime'] = pd.to_datetime(cc['Date/Time (LST)'])

# ── Filter both to 2025 ───────────────────────────────────────────────────
wc25 = wc[wc['Year'] == 2025].copy().reset_index(drop=True)
cc25 = cc[cc['Year'] == 2025].copy().reset_index(drop=True)

wc25 = wc25.set_index('datetime')
cc25 = cc25.set_index('datetime')

# ── Core columns we care about ────────────────────────────────────────────
CORE = ['Temp (°C)', 'Dew Point Temp (°C)', 'Rel Hum (%)',
        'Wind Dir (10s deg)', 'Wind Spd (km/h)',
        'Visibility (km)', 'Stn Press (kPa)',
        'Precip. Amount (mm)', 'Wind Chill', 'Weather']

# ── Use Pearson as base, fill gaps from City Centre ───────────────────────
weather = wc25[CORE].copy()
for col in CORE:
    if col in cc25.columns:
        mask = weather[col].isnull()
        weather.loc[mask, col] = cc25.loc[mask.index.intersection(cc25.index), col]

print(f"After merge — missing values:")
print(weather[CORE].isnull().sum())

# ── Feature engineering ───────────────────────────────────────────────────
# 1. Precipitation flags
weather['precip_mm']    = weather['Precip. Amount (mm)'].fillna(0)
weather['is_raining']   = weather['Weather'].str.contains(
                            r'[Rr]ain|[Dd]rizzle', na=False).astype(int)
weather['is_snowing']   = weather['Weather'].str.contains(
                            r'[Ss]now|[Bb]lizzard|[Ff]lurr', na=False).astype(int)
weather['is_fog']       = weather['Weather'].str.contains(
                            r'[Ff]og|[Mm]ist', na=False).astype(int)
weather['is_precip']    = ((weather['is_raining'] == 1) |
                            (weather['is_snowing'] == 1)).astype(int)

# 2. Wind speed category
weather['wind_cat'] = pd.cut(
    weather['Wind Spd (km/h)'].fillna(0),
    bins=[-1, 10, 20, 40, 9999],
    labels=['calm', 'light', 'moderate', 'strong']
)

# 3. Feels-like: use Wind Chill in winter, Humidex in summer, else Temp
weather['feels_like'] = np.where(
    weather['Wind Chill'].notna(),  weather['Wind Chill'],
    np.where(weather['Hmdx'].notna() if 'Hmdx' in weather.columns else False,
             weather.get('Hmdx', weather['Temp (°C)']),
             weather['Temp (°C)'])
)

# 4. Temperature bins
weather['temp_bin'] = pd.cut(
    weather['Temp (°C)'],
    bins=[-50, -10, 0, 5, 15, 25, 50],
    labels=['extreme_cold', 'cold', 'cool', 'mild', 'warm', 'hot']
)

# 5. Low visibility flag (< 5 km — affects driving conditions)
weather['low_visibility'] = (weather['Visibility (km)'] < 5).astype(int)

# 6. Date column for joining to delay data
weather['date'] = weather.index.date
weather['hour'] = weather.index.hour

print(f"\\nFinal shape: {weather.shape}")
print(f"\\nSample of engineered features:")
print(weather[['Temp (°C)', 'feels_like', 'temp_bin',
               'Wind Spd (km/h)', 'wind_cat',
               'is_raining', 'is_snowing', 'is_fog',
               'precip_mm', 'low_visibility']].head(8).to_string())

# ── Save ──────────────────────────────────────────────────────────────────
out_path = OUT_DIR / 'weather_2025.parquet'
weather.reset_index().to_parquet(out_path, index=False)
print(f"\\n✓ Saved → {out_path}  ({out_path.stat().st_size/1e6:.2f} MB)")

After merge — missing values:
Temp (°C)                 1
Dew Point Temp (°C)       1
Rel Hum (%)               1
Wind Dir (10s deg)       39
Wind Spd (km/h)           1
Visibility (km)           1
Stn Press (kPa)           1
Precip. Amount (mm)      27
Wind Chill             6531
Weather                4704
dtype: int64
\nFinal shape: (8760, 21)
\nSample of engineered features:
                     Temp (°C)  feels_like temp_bin  Wind Spd (km/h)  wind_cat  is_raining  is_snowing  is_fog  precip_mm  low_visibility
datetime
2025-01-01 00:00:00        1.6         1.6     cool             27.0  moderate           1           0       0        0.5               0
2025-01-01 01:00:00        1.6         1.6     cool             29.0  moderate           0           0       0        0.2               0
2025-01-01 02:00:00        1.4         1.4     cool             30.0  moderate           1           1       0        0.2               0
2025-01-01 03:00:00        0.8         0.8     cool             26.0  moderate           1           1       1        0.0               0
2025-01-01 04:00:00        1.4         1.4     cool             23.0  moderate           1           0       0        0.0               0
2025-01-01 05:00:00        1.0         1.0     cool             28.0  moderate           0           1       0        0.0               0
2025-01-01 06:00:00        1.5         1.5     cool             28.0  moderate           0           1       0        0.2               0
2025-01-01 07:00:00        1.9         1.9     cool             35.0  moderate           0           0       0        0.0               0
\n✓ Saved → ../data/processed/weather_2025.parquet  (0.18 MB)