In [3]:
import pandas as pd

In [4]:
# Load the processed data
print("Loading parquet data...")
df = pd.read_parquet("./tmp/unfv_with_weather_route_29_39.parquet")
print(f"Columns: {df.columns.tolist()}")

Loading parquet data...
Columns: ['route', 'trip_id', 'stopid', 'thrusteet', 'actual_arrival', 'hour', 'day_of_week', 'month', 'day_of_year', 'hour_sin', 'hour_cos', 'day_of_week_sin', 'day_of_week_cos', 'delay_seconds', 'nearest_whole_hour', 'Climate ID', 'Temp (°C)', 'Dew Point Temp (°C)', 'Rel Hum (%)', 'Wind Spd (km/h)', 'Visibility (km)', 'Stn Press (kPa)', 'Precip. Amount (mm)']

In [5]:
df.dtypes

route                         float64
trip_id                string[python]
stopid                 string[python]
thrusteet              string[python]
actual_arrival         datetime64[ns]
hour                            int32
day_of_week                     int32
month                           int32
day_of_year                     int32
hour_sin                      float64
hour_cos                      float64
day_of_week_sin               float64
day_of_week_cos               float64
delay_seconds                 float64
nearest_whole_hour     datetime64[ns]
Climate ID                    float64
Temp (°C)                     float64
Dew Point Temp (°C)           float64
Rel Hum (%)                   float64
Wind Spd (km/h)               float64
Visibility (km)               float64
Stn Press (kPa)               float64
Precip. Amount (mm)           float64
dtype: object

In [6]:
df_29 = df[df["route"] == 29]

In [7]:
df_29.isna().sum()

route                      0
trip_id                    0
stopid                     0
thrusteet              72138
actual_arrival             0
hour                       0
day_of_week                0
month                      0
day_of_year                0
hour_sin                   0
hour_cos                   0
day_of_week_sin            0
day_of_week_cos            0
delay_seconds              0
nearest_whole_hour         0
Climate ID               128
Temp (°C)                128
Dew Point Temp (°C)      128
Rel Hum (%)              128
Wind Spd (km/h)          128
Visibility (km)          128
Stn Press (kPa)          128
Precip. Amount (mm)      128
dtype: int64

In [8]:
df_29[df_29.stopid.str.contains("_")].stopid.value_counts().sum()

np.int64(78889)

In [9]:
def create_bound(stopid):
    if "_" in stopid:
        get_bound = stopid.split("_")[1]
        return int(get_bound)
    else:
        return 0

df_29['bound'] = df_29['stopid'].apply(create_bound)

/tmp/ipykernel_35534/1413578387.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_29['bound'] = df_29['stopid'].apply(create_bound)

In [10]:
df_29[df_29.stopid.str.contains("_")].bound.value_counts().sum()

np.int64(78889)

In [11]:
df_29['stopid'] = df_29['stopid'].apply(lambda x: int(x.split("_")[0]) if "_" in x else int(x))

/tmp/ipykernel_35534/1405639651.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_29['stopid'] = df_29['stopid'].apply(lambda x: int(x.split("_")[0]) if "_" in x else int(x))

In [12]:
df_29.dtypes

route                         float64
trip_id                string[python]
stopid                          int64
thrusteet              string[python]
actual_arrival         datetime64[ns]
hour                            int32
day_of_week                     int32
month                           int32
day_of_year                     int32
hour_sin                      float64
hour_cos                      float64
day_of_week_sin               float64
day_of_week_cos               float64
delay_seconds                 float64
nearest_whole_hour     datetime64[ns]
Climate ID                    float64
Temp (°C)                     float64
Dew Point Temp (°C)           float64
Rel Hum (%)                   float64
Wind Spd (km/h)               float64
Visibility (km)               float64
Stn Press (kPa)               float64
Precip. Amount (mm)           float64
bound                           int64
dtype: object

In [13]:
df_29.isna().sum()

route                      0
trip_id                    0
stopid                     0
thrusteet              72138
actual_arrival             0
hour                       0
day_of_week                0
month                      0
day_of_year                0
hour_sin                   0
hour_cos                   0
day_of_week_sin            0
day_of_week_cos            0
delay_seconds              0
nearest_whole_hour         0
Climate ID               128
Temp (°C)                128
Dew Point Temp (°C)      128
Rel Hum (%)              128
Wind Spd (km/h)          128
Visibility (km)          128
Stn Press (kPa)          128
Precip. Amount (mm)      128
bound                      0
dtype: int64

In [14]:
df_29_no_na_dropped = df_29.dropna(subset=['Climate ID', 'thrusteet'])

In [15]:
df_29_no_na_dropped.shape

(2018320, 24)

In [16]:
df_29_no_na_dropped.isna().sum()

route                  0
trip_id                0
stopid                 0
thrusteet              0
actual_arrival         0
hour                   0
day_of_week            0
month                  0
day_of_year            0
hour_sin               0
hour_cos               0
day_of_week_sin        0
day_of_week_cos        0
delay_seconds          0
nearest_whole_hour     0
Climate ID             0
Temp (°C)              0
Dew Point Temp (°C)    0
Rel Hum (%)            0
Wind Spd (km/h)        0
Visibility (km)        0
Stn Press (kPa)        0
Precip. Amount (mm)    0
bound                  0
dtype: int64

In [17]:
df_29_no_na_dropped.to_csv("./tmp/df_29_no_na_dropped_without_encoding.csv", index=False)

In [18]:
df_29_no_na_dropped['thrustreet'] = df_29_no_na_dropped['thrusteet']
df_29_no_na_dropped_encoding = pd.get_dummies(df_29_no_na_dropped, columns=['thrusteet'], prefix=['thrusteet'], dtype=int)

/tmp/ipykernel_35534/3855994633.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_29_no_na_dropped['thrustreet'] = df_29_no_na_dropped['thrusteet']

In [19]:
df_29_no_na_dropped_encoding.head(), df_29_no_na_dropped_encoding.shape

(   route    trip_id  stopid          actual_arrival  hour  day_of_week  month  \
 0   29.0   52553080   34800 2025-01-01 00:06:13.000     0            2      1
 2   29.0  172354080    1361 2025-01-01 00:07:26.027     0            2      1
 4   29.0   52553080    2815 2025-01-01 00:07:35.995     0            2      1
 6   29.0  172354080    9023 2025-01-01 00:07:58.226     0            2      1
 7   29.0   52553080   18388 2025-01-01 00:08:48.000     0            2      1

    day_of_year  hour_sin  hour_cos  ...       thrustreet  \
 0            1       0.0       1.0  ...    Princes' Blvd
 2            1       0.0       1.0  ...      Dufferin St
 4            1       0.0       1.0  ...  Saskatchewan Rd
 6            1       0.0       1.0  ...      Dufferin St
 7            1       0.0       1.0  ...      Dufferin St

    thrusteet_Dufferin St  thrusteet_Manitoba Dr thrusteet_Nova Scotia Ave  \
 0                      0                      0                         0
 2                      1                      0                         0
 4                      0                      0                         0
 6                      1                      0                         0
 7                      1                      0                         0

    thrusteet_Princes Blvd  thrusteet_Princes' Blvd  \
 0                       0                        1
 2                       0                        0
 4                       0                        0
 6                       0                        0
 7                       0                        0

    thrusteet_Princes' Gates Loop  thrusteet_Saskatchewan Rd  \
 0                              0                          0
 2                              0                          0
 4                              0                          1
 6                              0                          0
 7                              0                          0

    thrusteet_Wilson Ave  thrusteet_Wilson Station
 0                     0                         0
 2                     0                         0
 4                     0                         0
 6                     0                         0
 7                     0                         0

 [5 rows x 33 columns],
 (2018320, 33))

In [20]:
df_29_no_na_dropped_encoding.to_csv("./tmp/unfv_route_29_no_na_dropped_with_encoding.csv", index=False)

In [21]:
df_29_no_na_dropped_encoding[(df_29_no_na_dropped_encoding['nearest_whole_hour'] == '2025-01-01 07:00:00') & (df_29_no_na_dropped_encoding['hour'] == 7)][['Temp (°C)', 'actual_arrival', 'delay_seconds']]

      Temp (°C)          actual_arrival  delay_seconds
3365        1.9 2025-01-01 07:01:05.000         23.000
3376        1.9 2025-01-01 07:02:34.000         82.000
3379        1.9 2025-01-01 07:02:46.543         73.543
3382        1.9 2025-01-01 07:02:54.173        144.173
3384        1.9 2025-01-01 07:03:07.526        119.526
...         ...                     ...            ...
3635        1.9 2025-01-01 07:29:12.000        258.000
3636        1.9 2025-01-01 07:29:16.000       1224.000
3637        1.9 2025-01-01 07:29:16.002        246.002
3641        1.9 2025-01-01 07:29:37.000        356.000
3642        1.9 2025-01-01 07:29:40.000       1063.000

[127 rows x 3 columns]

In [22]:
df_29_no_na_dropped_encoding[(df_29_no_na_dropped_encoding['nearest_whole_hour'] == '2025-01-01 02:00:00') & (df_29_no_na_dropped_encoding['hour'] == 2)][['Temp (°C)', 'actual_arrival', 'delay_seconds']]

     Temp (°C)          actual_arrival  delay_seconds
595        1.4 2025-01-01 02:01:10.190         30.190
600        1.4 2025-01-01 02:01:29.479         20.479
602        1.4 2025-01-01 02:01:58.000        110.000
603        1.4 2025-01-01 02:02:00.000          5.000
605        1.4 2025-01-01 02:02:04.698        110.698
..         ...                     ...            ...
718        1.4 2025-01-01 02:28:16.600        133.600
719        1.4 2025-01-01 02:28:38.092        283.092
720        1.4 2025-01-01 02:29:20.585        267.585
721        1.4 2025-01-01 02:29:32.000        258.000
722        1.4 2025-01-01 02:29:41.000        221.000

[97 rows x 3 columns]

In [23]:
df_29_no_na_dropped_encoding[(df_29_no_na_dropped_encoding['month'] == 1) & (df_29_no_na_dropped_encoding['hour'] == 7)][['Temp (°C)', 'actual_arrival', 'delay_seconds']]

         Temp (°C)          actual_arrival  delay_seconds
3365           1.9 2025-01-01 07:01:05.000         23.000
3376           1.9 2025-01-01 07:02:34.000         82.000
3379           1.9 2025-01-01 07:02:46.543         73.543
3382           1.9 2025-01-01 07:02:54.173        144.173
3384           1.9 2025-01-01 07:03:07.526        119.526
...            ...                     ...            ...
3258325        0.2 2025-01-29 07:08:28.206        393.206
3258326        0.2 2025-01-29 07:08:53.702        363.702
3258329        0.2 2025-01-29 07:09:08.000        348.000
3258330        0.2 2025-01-29 07:09:48.825        313.825
3258332        0.2 2025-01-29 07:10:08.000        304.000

[534 rows x 3 columns]